spring:
  application:
    name: "Auth Test Dev"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

  mail:
    sender: anish@test.com
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAIL_TRAP_USERNAME}
    password: ${MAIL_TRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


server:
  port: 8082
  forward-headers-strategy: NATIVE
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.hc.client5.http.wire: DEBUG
security:
  credentials:
    admin: ${ADMIN_PASS}
    user: ${USER_PASS}
  jwt:
    secret: ${JWT_SECRET:OYG19RMnZBIKFGAWkInZ0sxUeNQwqAwf1jbUG4mJ6zCDRamP6pt2kyvk5fDJ9VnE}
    issuer: ${JWT_ISSUER:anish.raj}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:300}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_TOKEN_COOKIE_NAME:refreshCookie}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:None}
    cookie-domain:
  cors:
    allowed-urls: ${ALLOWED_URLS}
app:
  frontend:
    url: ${FRONTEND_URL}
  backend:
    url: ${BACKEND_URL}