spring:
  application:
    name: Auth Test Dev
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: anish@123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    user:
      name: root
      password: root
server:
  port: 8082
  servlet:
    context-path: /api
